name: CI Workflow

# trigger
on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-version-83:
   name: "Build the Laravel Application"
   uses: ./.github/workflows/build.yaml
   with:
     version: "8.3"
   secrets: 
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       

  test:
    needs: [build-version-83]
    name: "Test the Laravel Applicaion"
    uses: ./.github/workflows/test.yaml
    

  