name: QA workflow

on: workflow_dispatch
  
jobs:
 
  build-version-83:
   name: "Build the Laravel Application"
   uses: ./.github/workflows/build.yaml
   with:
     version: "8.3"
   secrets:
    SONAR_TOKEN: "sdsfdsjfjsdfjisjdfjdsi"
 

